from manim import *

# Dartboard
DARTBOARD_RADII = [1.25, 1, 0.75, 0.5]
DARTBOARD_COLOURS = [BLUE_E, WHITE, BLUE_E, WHITE]
DARTBOARD_CENTRE_COLOUR = GREEN

# Dartboard point (1 model)
DARTBOARD_DOT_COLOUR = YELLOW
DARTBOARD_DOT_STROKE_WIDTH = 0.4
DARTBOARD_DOT_STROKE_COLOUR = BLACK

# Dartboard point (1 ensemble model)
DARTBOARD_MODEL_COLOUR = GOLD_A
DARTBOARD_MODEL_STROKE_WIDTH = 0.4
DARTBOARD_MODEL_STROKE_COLOUR = BLACK
